### PR TITLE
chore: update nix versions

### PR DESCRIPTION
**Pull request by deemp**
@rickynils

### CODE REVIEW

**Comment by rickynils** [comment]
@deemp Thank you for this! I can't wrap my head around why the CI checks fail though. Can you rebase your PR the current master and see if that does the trick?

**Comment by deemp** [comment]
@rickynils, rebased.

Checks failed due to this error https://github.com/nixbuild/nix-quick-install-action/actions/runs/8222697904/job/22660983729#step:4:21

IDK the reason for this error, though.

**Comment by rickynils** [comment]
@deemp I think I figured it out. When you bumped the nixpkgs revision, `nix-2.3.16` also got bumped, to `nix-2.3.17`. This is fine, but you should add that change to `cicd.yml` too.

**Comment by deemp** [comment]
@rickynils, bumped

**Comment by deemp** [comment]
@rickynils, thanks!

**Pull request merged**
